Post meeting push: 3/2/2021
-Update test cases with removal of default
- Everything in test_simple.py works except for test_two_paths_by_len_and_color() --> line:167: assert damages.get(node, 0) == (influences[0]-influences[1])
=================
FAILED test_simple.py::test_two_paths_by_len_and_color - assert inf == (4 - 3)